### ISSUE TITLE
May I ask how you made the GBA-ex.svg?

### ISSUE THREAD

**Issue by demoliisher** [yusancky/GBA-ex#28]
I want to make a East Guangdong version (exactly the Chaoshan area). How can I take advantage of some existing data? If there are no way to follow, how can I draw the map by myself? Which software or site is recommended?

**Comment by yusancky** [comment]
I downloaded the [File:粤港澳大湾区示意图.svg on Wikimedia Commons](https://commons.m.wikimedia.org/wiki/File:%E7%B2%A4%E6%B8%AF%E6%BE%B3%E5%A4%A7%E6%B9%BE%E5%8C%BA%E7%A4%BA%E6%84%8F%E5%9B%BE.svg) as the base picture and made modifications on it using [Inkscape](https://inkscape.org/).

**Comment by yusancky** [comment]
> How can I take advantage of some existing data?

I downloaded the [File:粤港澳大湾区示意图.svg on Wikimedia Commons](https://commons.m.wikimedia.org/wiki/File:%E7%B2%A4%E6%B8%AF%E6%BE%B3%E5%A4%A7%E6%B9%BE%E5%8C%BA%E7%A4%BA%E6%84%8F%E5%9B%BE.svg) as the base picture.

> Which software or site is recommended?

I made modifications using [Inkscape](https://inkscape.org/).

To achieve such an interactive effect, all you need to do is delete unnecessary paths and set up groups, making the SVG image resemble the SVG library in the repo.
